CREATE DATABASE [QLTX]
GO
USE [QLTX]
GO
CREATE TABLE [LICHTRINH](
	[MA] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[THOIGIANBATDAU] [datetime] NOT NULL,
	[THOIGIANKETTHUC] [datetime] NOT NULL,
	[MATUYENDUONG] [int] NOT NULL,
	[NGAYPHANCONG] [date] NOT NULL,
	[MAXE] [int] NOT NULL,
	[NGUOICHINHSUACUOICUNG] [int] NOT NULL,
	[TAIXE] [int] NOT NULL
)
GO
CREATE TABLE [QUANLY](
	[MA] [int] PRIMARY KEY NOT NULL,
	[HOTEN] [nvarchar](50) NULL,
	[NGAYSINH] [date] NULL
)
GO
CREATE TABLE [QUANTRI](
	[MA] [int] PRIMARY KEY NOT NULL,
	[HOTEN] [nvarchar](50) NULL,
	[NGAYSINH] [date] NULL
)
GO
CREATE TABLE [TAIKHOAN](
	[MA] [int] PRIMARY KEY NOT NULL,
	[TAIKHOAN] [nchar](20) NULL,
	[MATKHAU] [nchar](10) NULL,
	[LOAINGUOIDUNG] [nvarchar](50) NULL
)
GO
CREATE TABLE [TAIXE](
	[MA] [int] PRIMARY KEY NOT NULL,
	[TEN] [nvarchar](50) NULL,
	[CMND] [nchar](10) NULL,
	[NGAYSINH] [date] NOT NULL,
	[VITRI] [nchar](10) NOT NULL,
	[MATO] [int] NOT NULL,
	[QUANGDUONGDIDUOC] [int] NOT NULL
)
GO
CREATE TABLE [TO](
	[MA] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[TEN] [nvarchar](50) NULL,
	[TOTRUONG] [int] NULL
)
GO
CREATE TABLE [TUYENDUONG](
	[MA] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[TEN] [nvarchar](50) NULL,
	[CHIEUDAI] [int] NOT NULL,
	[DIEMBATDAU] [nvarchar](50) NOT NULL,
	[DIEMKETTHUC] [nvarchar](50) NOT NULL
)
GO
CREATE TABLE [XE](
	[MA] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[BIENSO] [nchar](20) NOT NULL,
	[TINHTRANG] [nvarchar](50) NOT NULL
)
GO
ALTER TABLE [LICHTRINH]  WITH CHECK ADD  CONSTRAINT [FK_LICHTRINH_TAIXE] FOREIGN KEY([TAIXE])
REFERENCES [TAIXE] ([MA])
GO
ALTER TABLE [LICHTRINH] CHECK CONSTRAINT [FK_LICHTRINH_TAIXE]
GO
ALTER TABLE [LICHTRINH]  WITH CHECK ADD  CONSTRAINT [FK_LICHTRINH_TUYENDUONG] FOREIGN KEY([MATUYENDUONG])
REFERENCES [TUYENDUONG] ([MA])
GO
ALTER TABLE [LICHTRINH] CHECK CONSTRAINT [FK_LICHTRINH_TUYENDUONG]
GO
ALTER TABLE [LICHTRINH]  WITH CHECK ADD  CONSTRAINT [FK_LICHTRINH_XE] FOREIGN KEY([MAXE])
REFERENCES [XE] ([MA])
GO
ALTER TABLE [LICHTRINH] CHECK CONSTRAINT [FK_LICHTRINH_XE]
GO
ALTER TABLE [QUANLY]  WITH CHECK ADD  CONSTRAINT [FK_QUANLY_TAIKHOAN] FOREIGN KEY([MA])
REFERENCES [TAIKHOAN] ([MA])
GO
ALTER TABLE [QUANLY] CHECK CONSTRAINT [FK_QUANLY_TAIKHOAN]
GO
ALTER TABLE [QUANTRI]  WITH CHECK ADD  CONSTRAINT [FK_QUANTRI_TAIKHOAN] FOREIGN KEY([MA])
REFERENCES [TAIKHOAN] ([MA])
GO
ALTER TABLE [QUANTRI] CHECK CONSTRAINT [FK_QUANTRI_TAIKHOAN]
GO
ALTER TABLE [TAIXE]  WITH CHECK ADD  CONSTRAINT [FK_TAIXE_TAIKHOAN] FOREIGN KEY([MA])
REFERENCES [TAIKHOAN] ([MA])
GO
ALTER TABLE [TAIXE] CHECK CONSTRAINT [FK_TAIXE_TAIKHOAN]
GO
ALTER TABLE [TAIXE]  WITH CHECK ADD  CONSTRAINT [FK_TAIXE_TO] FOREIGN KEY([MATO])
REFERENCES [TO] ([MA])
GO
ALTER TABLE [TAIXE] CHECK CONSTRAINT [FK_TAIXE_TO]
GO
ALTER TABLE [TO]  WITH CHECK ADD  CONSTRAINT [FK_TO_TAIXE1] FOREIGN KEY([TOTRUONG])
REFERENCES [TAIXE] ([MA])
GO
ALTER TABLE [TO] CHECK CONSTRAINT [FK_TO_TAIXE1]
